# Getting started with pandas

In [132]:
from pandas import Series, DataFrame
import pandas as pd

In [133]:
from __future__ import division
from numpy.random import randn
import numpy as np
import os
import matplotlib.pyplot as plt
np.random.seed(12345)
plt.rc('figure', figsize=(10, 6))
from pandas import Series, DataFrame
import pandas as pd
np.set_printoptions(precision=4)

In [134]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = 'all'

In [3]:
%pwd

'D:\\DEV64\\dev_python\\pydata-book-1st-edition'

## Introduction to pandas data structures

### Series

In [4]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
type(obj.values)

numpy.ndarray

In [7]:
obj.values?

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
type(obj.index)

pandas.core.indexes.range.RangeIndex

In [10]:
list(obj.index)

[0, 1, 2, 3]

In [11]:
np.array(obj.index)

array([0, 1, 2, 3], dtype=int64)

In [12]:
tuple(obj.index)

(0, 1, 2, 3)

In [13]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [15]:
obj2['a']

-5

In [16]:
obj2['d'] = 6
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [17]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [18]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [19]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [21]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [22]:
'b' in obj2

True

In [23]:
'e' in obj2

False

In [24]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [25]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [28]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [34]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [35]:
name =Series([1,2,3,4], index = ['Bob', 'Bob', 'Ryan','King'])
name

Bob     1
Bob     2
Ryan    3
King    4
dtype: int64

In [39]:
obj + name
name + name

Bob      5.0
Bob      6.0
Jeff     NaN
King     NaN
Ryan     6.0
Steve    NaN
dtype: float64

Bob     2
Bob     4
Ryan    6
King    8
dtype: int64

### DataFrame

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [42]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [43]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [44]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [45]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [46]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [47]:
type(frame2['state'])

pandas.core.series.Series

In [48]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [49]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [50]:
frame2.ix?

In [135]:
frame2.ix['three']

D:\anaconda\envs\da36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


KeyError: 'three'

In [52]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [53]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [54]:
frame2.debt

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
Name: debt, dtype: object

In [55]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [56]:
frame2['debt'] = np.arange(5.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [57]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five']); val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [58]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [59]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [60]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [61]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [62]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}} # 사전이 중첩된 형태.

In [63]:
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [64]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [65]:
DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [66]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [67]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [68]:
frame3.index.name = 'year'; frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [69]:
frame3.index.name

'year'

In [70]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [71]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

### Index objects

In [72]:
obj = Series(range(3), index=['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [73]:
index[1:]

Index(['b', 'c'], dtype='object')

In [74]:
index[1] = 'd' #색인(index) 객체는 변경할 수 없다.

TypeError: Index does not support mutable operations

In [75]:
index = pd.Index(np.arange(3))
index

Int64Index([0, 1, 2], dtype='int64')

In [76]:
obj2 = Series([1.5, -2.5, 0], index=[1, 2, 3])
obj2

1    1.5
2   -2.5
3    0.0
dtype: float64

In [77]:
obj2.index is index

False

In [78]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [79]:
'Ohio' in frame3.columns

True

In [80]:
2003 in frame3.index

False

## Essential functionality

### Reindexing

In [81]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [82]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [83]:
obj.a = -5.1

In [84]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [85]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.1
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [86]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [93]:
#loc, iloc
obj3.loc[2] # obj3 에서 loc는 2에 매칭되는 값. 몇번째 데이터
obj3.iloc[2] #iloc는 index location값을 찾는거.
#위의 방식으로 사용하는 것이 훨씬 낫습니다. 혼동되지않거든.
obj3[2] # 레이블로 인식한다.
#obj3[1] #인덱스가 정수가 아니라면! 오류가 날수도 있습니다.

obj2[2]
obj2[1]

'purple'

'yellow'

'purple'

3.6

7.2

In [94]:
obj3.reindex(range(6)) #NaN =  null

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [87]:
obj3.reindex(range(6), method='ffill') #ffill은 null값을 그대로 채워라! 

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [88]:
frame = DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                  columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [95]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [96]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [97]:
np.sort(states)

array(['California', 'Texas', 'Utah'], dtype='<U10')

In [98]:
# 보간 (interpolation)은 로우에 대해서만 이루어 짐
#따라서 아래는 로우와 컬럼에 대해 보간을 수행하려고 하므로 에러가 발생하는 것이다.
frame.reindex(index=['a', 'b', 'c', 'd'], method='bfill',
              columns=states)

ValueError: index must be monotonic increasing or decreasing

In [99]:
frame.ix[['a', 'b', 'c', 'd'], states]

D:\anaconda\envs\da36\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping entries from an axis

In [100]:
obj = Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [101]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [102]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [103]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [104]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [105]:
data.drop(['two', 'four'], axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Indexing, selection, and filtering

In [113]:
obj = Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj['b']
obj.b

1.0

1.0

In [116]:
obj
obj[1]
obj.iloc[1] #위랑 같은 방법.

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

1.0

1.0

In [115]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [109]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [110]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [111]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [112]:
obj['b':'c'] #레이블에 대해 슬라이싱 할때는, 두번째 나오는 것도 포함된다.  - 'b':'c'라면 c까지 포함하는 것.

b    1.0
c    2.0
dtype: float64

In [117]:
obj['b':'c'] = 5 #슬라이싱 한 놈들에게 5를 넣어주겠습니다.
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [118]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [119]:
data['two']  # == data.two 

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [120]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [121]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [122]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [123]:
s = Series([True, False, False, True], 
           index=['Ohio', 'Utah', 'Colorado', 'New York'])

In [124]:
s

Ohio         True
Utah        False
Colorado    False
New York     True
dtype: bool

In [125]:
data[s]

D:\anaconda\envs\da36\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


one  two  three  four
Ohio        0    1      2     3
New York   12   13     14    15

In [126]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [129]:
data[data < 5] = 0

In [130]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [137]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [138]:
#data.loc[['Colorado','Utah'],[3,0,1]] : error
data.loc[['Colorado','Utah'],['four','one','two']]
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [139]:
data.ix[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [140]:
data.ix[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [141]:
data.ix[data.three > 5, :3] 

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [159]:
#테스트 : 아래 색인 결과를 예측해보자.
obj = Series(np.arange(7) ** 2)
obj[2:4]
obj.loc[2:4]
obj.iloc[2:4]

2    4
3    9
dtype: int32

2     4
3     9
4    16
dtype: int32

2    4
3    9
dtype: int32


### Arithmetic and data alignment

In [142]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [143]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [144]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [145]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [146]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = 'all'

In [147]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1
df2

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [148]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

#### Arithmetic methods with fill values

In [149]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1
df2

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [150]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [151]:
df1.add(df2, fill_value=0) #add = 덧셈하는 메소드

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [152]:
df1.reindex(columns=df2.columns)
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [153]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [154]:
df1.reindex(index=df2.index, columns=df2.columns, fill_value=0)

a    b     c     d    e
0  0.0  1.0   2.0   3.0  0.0
1  4.0  5.0   6.0   7.0  0.0
2  8.0  9.0  10.0  11.0  0.0
3  0.0  0.0   0.0   0.0  0.0

#### Operations between DataFrame and Series

In [155]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [156]:
arr[0]

array([0., 1., 2., 3.])

In [157]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [158]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame.loc['Utah']
series
frame

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [160]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [161]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [162]:
series2 = Series(range(3), index=['b', 'e', 'f'])
series2

b    0
e    1
f    2
dtype: int64

In [163]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [164]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [165]:
series3 = frame['d']
frame
series3

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [166]:
frame - series3 #axis는 1인 상태.

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [167]:
frame.sub(series3, axis=0) #적용하는 축방향이 axis= 0 일 뿐이지 위의 - 와 같은 식. sub

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function application and mapping

In [ ]:
frame = DataFrame(np.random.randn(4, 3), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])

frame

In [ ]:
np.abs(frame)

In [ ]:
f = lambda x: x.max() - x.min()

In [ ]:
frame.apply(f)

In [ ]:
frame.apply(f, axis=1)

In [ ]:
def f(x):
    return Series([x.min(), x.max()], index=['min', 'max'])

In [ ]:
frame.apply(f)

In [ ]:
frame

In [ ]:
frame.apply(f, axis=1).T

In [ ]:
format = lambda x: '%.2f' % x

In [ ]:
frame.applymap(format)

In [ ]:
frame['e'].map(format)

### Sorting and ranking

In [ ]:
obj = Series(range(4), index=['d', 'a', 'b', 'c'])
obj
obj.sort_index()

In [ ]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
frame

In [ ]:
frame.sort_index()

In [ ]:
frame.sort_index(axis=1)

In [ ]:
frame.sort_index(axis=1, ascending=False)

In [ ]:
frame = DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

In [ ]:
frame.sort_values(by='a')

In [ ]:
obj = Series([4, 7, -3, 2])

In [ ]:
obj.sort_values()

In [ ]:
frame.sort_values(by=['a', 'b'])

In [ ]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

In [ ]:
obj.rank(method='first')

In [ ]:
obj.rank(ascending=False, method='max')

In [ ]:
frame = DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                   'c': [-2, 5, 8, -2.5]})
frame

In [ ]:
frame.rank(axis=0)

In [ ]:
frame.rank(axis=1)

### Axis indexes with duplicate values

In [ ]:
obj = Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

In [ ]:
obj.index.is_unique

In [ ]:
obj['a']

In [ ]:
obj['c']

In [ ]:
df = DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

In [ ]:
df.loc['b']

In [ ]:
df.iloc[2:4]

## Summarizing and computing descriptive statistics

In [ ]:
df = DataFrame([[1.4, np.nan], [7.1, -4.5],
                [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])
df

In [ ]:
df.sum()

In [ ]:
df.sum(axis=1)

In [ ]:
df.mean(axis=1, skipna=False)

In [ ]:
df.idxmax()

In [ ]:
df.cumsum()

In [ ]:
df.describe()

In [ ]:
obj = Series(['a', 'a', 'b', 'c'] * 4)
obj.describe()

### Correlation and covariance

In [ ]:
#import pandas.io.data as web
import pandas_datareader as web

all_data = {}
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker)
all_data

In [ ]:
price = DataFrame({tic: data['Adj Close']
                   for tic, data in all_data.items()})
volume = DataFrame({tic: data['Volume']
                    for tic, data in all_data.items()})

In [ ]:
returns = price.pct_change()
returns.tail()

In [ ]:
returns.MSFT.corr(returns.IBM)

In [ ]:
returns.MSFT.cov(returns.IBM)

In [ ]:
returns.corr()

In [ ]:
returns.cov()

In [ ]:
returns.corrwith(returns.IBM)

In [ ]:
returns.corrwith(volume)

### Unique values, value counts, and membership

In [ ]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [ ]:
uniques = obj.unique()
uniques

In [ ]:
obj.value_counts()

In [ ]:
pd.value_counts(obj.values, sort=False)

In [ ]:
mask = obj.isin(['b', 'c'])
mask

In [ ]:
obj[mask]

In [ ]:
data = DataFrame({'Qu1': [1, 3, 4, 3, 4],
                  'Qu2': [2, 3, 1, 2, 3],
                  'Qu3': [1, 5, 2, 4, 4]})
data

In [ ]:
result = data.apply(pd.value_counts).fillna(0)
result

## Handling missing data

In [ ]:
string_data = Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

In [ ]:
string_data.isnull()

In [ ]:
string_data[0] = None
string_data.isnull()

### Filtering out missing data

In [ ]:
from numpy import nan as NA
data = Series([1, NA, 3.5, NA, 7])
data.dropna()

In [ ]:
data[data.notnull()]

In [ ]:
data = DataFrame([[1., 6.5, 3.], [1., NA, NA],
                  [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

In [ ]:
cleaned

In [ ]:
data.dropna(how='all')

In [ ]:
data[4] = NA
data

In [ ]:
data.dropna(axis=1, how='all')

In [ ]:
df = DataFrame(np.random.randn(7, 3))
df.loc[:4, 1] = NA; df.loc[:2, 2] = NA
df

In [ ]:
df.dropna(thresh=3)

### Filling in missing data

In [ ]:
df.fillna(0)

In [ ]:
df.fillna({1: 0.5, 3: -1})

In [ ]:
# always returns a reference to the filled object
_ = df.fillna(0, inplace=True)
df

In [ ]:
df = DataFrame(np.random.randn(6, 3))
df.loc[2:, 1] = NA; df.loc[4:, 2] = NA
df

In [ ]:
df.fillna(method='ffill')

In [ ]:
df.fillna(method='ffill', limit=2)

In [ ]:
data = Series([1., NA, 3.5, NA, 7])
data.mean()

In [ ]:
data.fillna(data.mean())

## Hierarchical indexing

In [ ]:
data = Series(np.random.randn(10),
              index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                     [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])
data

In [ ]:
data.index

In [ ]:
data['b']

In [ ]:
data['b':'c']

In [ ]:
data.loc[['b', 'd']]

In [ ]:
data[:, 2]

In [ ]:
data.unstack()

In [ ]:
data.unstack().stack()

In [ ]:
data.unstack(level=-1)

In [ ]:
frame = DataFrame(np.arange(12).reshape((4, 3)),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=[['Ohio', 'Ohio', 'Colorado'],
                           ['Green', 'Red', 'Green']])
frame

In [ ]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

In [ ]:
frame['Ohio']


### Reordering and sorting levels

In [ ]:
frame
frame.swaplevel('key1', 'key2')

In [ ]:
#frame.sortlevel(1)
frame.sort_index(level=1)

In [ ]:
#frame.swaplevel(0, 1).sortlevel(0)
frame.swaplevel(0, 1).sort_index(level=0)

### Summary statistics by level

In [ ]:
frame
frame.sum(level='key2')

In [ ]:
frame.sum(level='color', axis=1)

### Using a DataFrame's columns

In [ ]:
frame = DataFrame({'a': range(7), 'b': range(7, 0, -1),
                   'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
                   'd': [0, 1, 2, 0, 1, 2, 3]})
frame

In [ ]:
frame2 = frame.set_index(['c', 'd'])
frame2

In [ ]:
frame.set_index(['c', 'd'], drop=False)

In [ ]:
frame2.reset_index()

## Other pandas topics

### Integer indexing

In [ ]:
ser = Series(np.arange(3.))
ser.iloc[-1]
ser[-1]

In [ ]:
ser

In [ ]:
ser2 = Series(np.arange(3.), index=['a', 'b', 'c'])
ser2
ser2.iloc[:1]

In [ ]:
ser.loc[:1]

In [ ]:
ser3 = Series(range(3), index=[-5, 1, 3])
ser3
ser3.iloc[2]
ser3.loc[-5]

In [ ]:
frame = DataFrame(np.arange(6).reshape((3, 2)), index=[2, 0, 1])
frame
frame.iloc[0]

### Panel data

In [ ]:
#import pandas.io.data as web
import pandas_datareader as web

pdata = pd.Panel(dict((stk, web.get_data_yahoo(stk))
                       for stk in ['AAPL', 'GOOG', 'MSFT', 'IBM']))

In [ ]:
pdata

In [ ]:
pdata = pdata.swapaxes('items', 'minor')
pdata

In [ ]:
pdata['Adj Close']

In [ ]:
pdata.loc[:, '6/1/2012', :]

In [ ]:
pdata.loc['Adj Close', '5/22/2012':, :]

In [ ]:
stacked = pdata.loc[:, '5/30/2012':, :].to_frame()
stacked

In [ ]:
stacked.to_panel()